apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9090"
    spec:
      containers:
        - name: backend
          image: ghcr.io/william-wtr92/agentkit-fastapi:latest
          ports:
            - containerPort: 9090
          ## TODO: Add environment variables
      imagePullSecrets:
        - name: github-regcred