apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "3000"
    spec:
      containers:
        - name: client
          image: ghcr.io/william-wtr92/agentkit-frontend:latest
          ports:
            - containerPort: 3000
          ## TODO: Add environment variables
          env:
            - name: NODE_ENV
              value: "production"
      imagePullSecrets:
        - name: github-regcred